project_id = "zbtgonklxweikgukzukg"

[functions.os-create-checkout]
verify_jwt = false

[functions.os-stripe-connect]
verify_jwt = false

[functions.os-stripe-webhook]
verify_jwt = false

[functions.os-communications]
verify_jwt = false

[functions.os-results]
verify_jwt = false

[functions.os-waves]
verify_jwt = false

[functions.os-account]
verify_jwt = false

[functions.os-series]
verify_jwt = false
